;---------------------------------------------------------- v 1.5.0 ----
include     resources.inc
include     windows.inc

include     kernel32.inc
include     user32.inc
include     advapi32.inc
include     gdi32.inc
include     masm32.inc

includelib  kernel32.lib
includelib  user32.lib
includelib  advapi32.lib
includelib  gdi32.lib
includelib  masm32.lib

include     macros.asm

include     parser.inc
include     parser.core.asm
;-----------------------------------------------------------------------
